// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const MemberRole = {
    /**
     * Sees the projects of their teams.
     */
    Member: "member",
    /**
     * Manages the projects and teams of the organization.
     */
    Admin: "admin",
    /**
     * Admin who also invites and removes members.
     */
    Manager: "manager",
    /**
     * Full control including deleting the organization.
     */
    Owner: "owner",
} as const;

export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];

export const MonitorType = {
    /**
     * HTTP HEAD request; up when the URL answers.
     */
    Ping: "Ping",
    /**
     * HTTP GET request; up when the status matches expectedStatus and the body contains expectedBody.
     */
    GET: "GET",
    /**
     * HTTP POST request; up when the status matches expectedStatus and the body contains expectedBody.
     */
    POST: "POST",
    /**
     * TCP connection to host:port given as url.
     */
    TCPPort: "TCP Port",
    /**
     * Certificate validity of the URL's host.
     */
    SSL: "SSL",
    /**
     * Up while an external service keeps calling heartbeatEndpoint within interval.
     */
    Heartbeat: "Heartbeat",
} as const;

export type MonitorType = (typeof MonitorType)[keyof typeof MonitorType];
