// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("glitchtip");

/**
 * API token of a GlitchTip user (Profile > Auth Tokens), or the token issued by a Bootstrap resource. Defaults to the GLITCHTIP_API_TOKEN environment variable. May be omitted for a provider that only creates Bootstrap resources.
 */
export declare const apiToken: string;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken") ?? (utilities.getEnv("GLITCHTIP_API_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * Origin of the GlitchTip instance, e.g. https://glitchtip.example.com. Defaults to the GLITCHTIP_BASE_URL environment variable.
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("GLITCHTIP_BASE_URL") || "");
    },
    enumerable: true,
});

