// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface AlertRecipientArgs {
    /**
     * Zulip bot API key; zulip only.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Zulip bot email; zulip only.
     */
    botEmail?: pulumi.Input<string | undefined>;
    /**
     * Zulip channel; zulip only.
     */
    channel?: pulumi.Input<string | undefined>;
    /**
     * Kind of target: email (the project's team members), webhook (Slack-compatible, works with Mattermost incoming webhooks), discord, googlechat, teams, ntfy, feishu or zulip.
     */
    recipientType: pulumi.Input<string>;
    /**
     * Event tags to include in the notification.
     */
    tagsToAdd?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Zulip topic; zulip only. Defaults to "GlitchTip Alerts".
     */
    topic?: pulumi.Input<string | undefined>;
    /**
     * Webhook URL. Required for every type except email.
     */
    url?: pulumi.Input<string | undefined>;
}

export interface KeyRateLimitArgs {
    /**
     * Maximum number of events accepted per window.
     */
    count: pulumi.Input<number>;
    /**
     * Length of the rate limit window in seconds.
     */
    window: pulumi.Input<number>;
}
