// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface AlertRecipient {
    /**
     * Zulip bot API key; zulip only.
     */
    apiKey?: string;
    /**
     * Zulip bot email; zulip only.
     */
    botEmail?: string;
    /**
     * Zulip channel; zulip only.
     */
    channel?: string;
    /**
     * Kind of target: email (the project's team members), webhook (Slack-compatible, works with Mattermost incoming webhooks), discord, googlechat, teams, ntfy, feishu or zulip.
     */
    recipientType: string;
    /**
     * Event tags to include in the notification.
     */
    tagsToAdd?: string[];
    /**
     * Zulip topic; zulip only. Defaults to "GlitchTip Alerts".
     */
    topic?: string;
    /**
     * Webhook URL. Required for every type except email.
     */
    url?: string;
}

export interface KeyRateLimit {
    /**
     * Maximum number of events accepted per window.
     */
    count: number;
    /**
     * Length of the rate limit window in seconds.
     */
    window: number;
}

