// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Issues an API token of a GlitchTip user without user interaction, for use as the apiToken of a second provider instance. The resource logs in with the user's email and password through the same endpoints as the web UI, waits for a freshly deployed instance to answer, and adopts an existing token with the same label and scopes before issuing a new one. A refresh that finds the token revoked, or the recorded host unreachable, marks the resource for repair, and the next update issues a replacement token against the declared host. Deleting the resource revokes the token and keeps the user. The resource ID is the email.
 */
export class Bootstrap extends pulumi.CustomResource {
    /**
     * Get an existing Bootstrap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bootstrap {
        return new Bootstrap(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:Bootstrap';

    /**
     * Returns true if the given object is an instance of Bootstrap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bootstrap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bootstrap.__pulumiType;
    }

    /**
     * Origin of the GlitchTip instance. Defaults to the provider's base URL.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;
    /**
     * Email of the user whose token is issued. Changing it replaces the resource.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Password of the user. The resource never changes it; keep it in sync with the deployed INITIAL_USER_PASSWORD.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * Seconds to wait for the instance to answer before giving up on create and update. Defaults to 180.
     */
    declare public readonly readyTimeoutSeconds: pulumi.Output<number>;
    /**
     * True after a refresh found the token revoked or the recorded host unreachable. The next update issues a replacement token.
     */
    declare public /*out*/ readonly repairRequired: pulumi.Output<boolean | undefined>;
    /**
     * Scopes of the API token, e.g. project:read. Changing them rotates the token. Defaults to every scope GlitchTip offers.
     */
    declare public readonly scopes: pulumi.Output<string[] | undefined>;
    /**
     * The issued API token. Use it as the apiToken of a second provider instance.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * ID of the issued API token.
     */
    declare public /*out*/ readonly tokenId: pulumi.Output<string>;
    /**
     * Label of the API token. Changing it rotates the token. Defaults to "pulumi".
     */
    declare public readonly tokenLabel: pulumi.Output<string>;

    /**
     * Create a Bootstrap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BootstrapArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["email"] = args?.email;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["readyTimeoutSeconds"] = (args?.readyTimeoutSeconds) ?? 180;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["tokenLabel"] = (args?.tokenLabel) ?? "pulumi";
            resourceInputs["repairRequired"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
        } else {
            resourceInputs["baseUrl"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["readyTimeoutSeconds"] = undefined /*out*/;
            resourceInputs["repairRequired"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
            resourceInputs["tokenLabel"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["email"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Bootstrap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bootstrap resource.
 */
export interface BootstrapArgs {
    /**
     * Origin of the GlitchTip instance. Defaults to the provider's base URL.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Email of the user whose token is issued. Changing it replaces the resource.
     */
    email: pulumi.Input<string>;
    /**
     * Password of the user. The resource never changes it; keep it in sync with the deployed INITIAL_USER_PASSWORD.
     */
    password: pulumi.Input<string>;
    /**
     * Seconds to wait for the instance to answer before giving up on create and update. Defaults to 180.
     */
    readyTimeoutSeconds?: pulumi.Input<number | undefined>;
    /**
     * Scopes of the API token, e.g. project:read. Changing them rotates the token. Defaults to every scope GlitchTip offers.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Label of the API token. Changing it rotates the token. Defaults to "pulumi".
     */
    tokenLabel?: pulumi.Input<string | undefined>;
}
