// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { BootstrapArgs } from "./bootstrap";
export type Bootstrap = import("./bootstrap").Bootstrap;
export const Bootstrap: typeof import("./bootstrap").Bootstrap = null as any;
utilities.lazyLoad(exports, ["Bootstrap"], () => require("./bootstrap"));

export { OrganizationArgs } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationMemberArgs } from "./organizationMember";
export type OrganizationMember = import("./organizationMember").OrganizationMember;
export const OrganizationMember: typeof import("./organizationMember").OrganizationMember = null as any;
utilities.lazyLoad(exports, ["OrganizationMember"], () => require("./organizationMember"));

export { ProjectArgs } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProjectAlertArgs } from "./projectAlert";
export type ProjectAlert = import("./projectAlert").ProjectAlert;
export const ProjectAlert: typeof import("./projectAlert").ProjectAlert = null as any;
utilities.lazyLoad(exports, ["ProjectAlert"], () => require("./projectAlert"));

export { ProjectKeyArgs } from "./projectKey";
export type ProjectKey = import("./projectKey").ProjectKey;
export const ProjectKey: typeof import("./projectKey").ProjectKey = null as any;
utilities.lazyLoad(exports, ["ProjectKey"], () => require("./projectKey"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { TeamArgs } from "./team";
export type Team = import("./team").Team;
export const Team: typeof import("./team").Team = null as any;
utilities.lazyLoad(exports, ["Team"], () => require("./team"));

export { UptimeMonitorArgs } from "./uptimeMonitor";
export type UptimeMonitor = import("./uptimeMonitor").UptimeMonitor;
export const UptimeMonitor: typeof import("./uptimeMonitor").UptimeMonitor = null as any;
utilities.lazyLoad(exports, ["UptimeMonitor"], () => require("./uptimeMonitor"));


// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "glitchtip:index:Bootstrap":
                return new Bootstrap(name, <any>undefined, { urn })
            case "glitchtip:index:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "glitchtip:index:OrganizationMember":
                return new OrganizationMember(name, <any>undefined, { urn })
            case "glitchtip:index:Project":
                return new Project(name, <any>undefined, { urn })
            case "glitchtip:index:ProjectAlert":
                return new ProjectAlert(name, <any>undefined, { urn })
            case "glitchtip:index:ProjectKey":
                return new ProjectKey(name, <any>undefined, { urn })
            case "glitchtip:index:Team":
                return new Team(name, <any>undefined, { urn })
            case "glitchtip:index:UptimeMonitor":
                return new UptimeMonitor(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("glitchtip", "index", _module)
pulumi.runtime.registerResourcePackage("glitchtip", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:glitchtip") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
