// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A member of a GlitchTip organization. Creating the resource invites the email address with the role and team memberships and sends the invitation mail; an existing member or pending invitation with that email is adopted and brought to the declared role and teams. With ENABLE_USER_REGISTRATION off, GlitchTip only invites emails of users that already exist on the instance. The resource ID is <organizationSlug>/<memberId>. Deleting the resource removes the member from the organization; GlitchTip refuses to remove the organization owner and the last member.
 */
export class OrganizationMember extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationMember resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OrganizationMember {
        return new OrganizationMember(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:OrganizationMember';

    /**
     * Returns true if the given object is an instance of OrganizationMember.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationMember {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationMember.__pulumiType;
    }

    /**
     * Email address of the member. Changing it replaces the resource.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Numeric ID of the membership.
     */
    declare public /*out*/ readonly memberId: pulumi.Output<string>;
    /**
     * Slug of the organization.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * True while the invitation has not been accepted.
     */
    declare public /*out*/ readonly pending: pulumi.Output<boolean>;
    /**
     * Organization role: member, admin, manager or owner. Defaults to member. GlitchTip keeps at least one owner.
     */
    declare public readonly role: pulumi.Output<enums.MemberRole | undefined>;
    /**
     * Slugs of the teams the member belongs to. Teams not listed are left, so the list is authoritative.
     */
    declare public readonly teams: pulumi.Output<string[] | undefined>;

    /**
     * Create a OrganizationMember resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrganizationMemberArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["role"] = args?.role;
            resourceInputs["teams"] = args?.teams;
            resourceInputs["memberId"] = undefined /*out*/;
            resourceInputs["pending"] = undefined /*out*/;
        } else {
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["memberId"] = undefined /*out*/;
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["pending"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["teams"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["email", "organizationSlug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(OrganizationMember.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a OrganizationMember resource.
 */
export interface OrganizationMemberArgs {
    /**
     * Email address of the member. Changing it replaces the resource.
     */
    email: pulumi.Input<string>;
    /**
     * Slug of the organization.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Organization role: member, admin, manager or owner. Defaults to member. GlitchTip keeps at least one owner.
     */
    role?: pulumi.Input<enums.MemberRole | undefined>;
    /**
     * Slugs of the teams the member belongs to. Teams not listed are left, so the list is authoritative.
     */
    teams?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
