// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A DSN key of a GlitchTip project, in addition to the key GlitchTip creates with the project (see Project.dsn). The resource ID is <organizationSlug>/<projectSlug>/<keyId>. Deleting the resource revokes the key, so clients using its DSN stop reporting.
 */
export class ProjectKey extends pulumi.CustomResource {
    /**
     * Get an existing ProjectKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ProjectKey {
        return new ProjectKey(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:ProjectKey';

    /**
     * Returns true if the given object is an instance of ProjectKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectKey.__pulumiType;
    }

    /**
     * Security endpoint of the key for Content-Security-Policy report-uri and Expect-CT reports.
     */
    declare public /*out*/ readonly cspReportUri: pulumi.Output<string>;
    /**
     * Public DSN clients report to.
     */
    declare public /*out*/ readonly dsn: pulumi.Output<string>;
    /**
     * UUID of the key.
     */
    declare public /*out*/ readonly keyId: pulumi.Output<string>;
    /**
     * Display name of the key.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * Slug of the organization the project belongs to.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * Slug of the project the key belongs to.
     */
    declare public readonly projectSlug: pulumi.Output<string>;
    /**
     * Public key part of the DSN.
     */
    declare public /*out*/ readonly public: pulumi.Output<string>;
    /**
     * Rate limit of the key. Unset accepts every event.
     */
    declare public readonly rateLimit: pulumi.Output<outputs.KeyRateLimit | undefined>;

    /**
     * Create a ProjectKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectKeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            if (args?.projectSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectSlug'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["projectSlug"] = args?.projectSlug;
            resourceInputs["rateLimit"] = args?.rateLimit;
            resourceInputs["cspReportUri"] = undefined /*out*/;
            resourceInputs["dsn"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
        } else {
            resourceInputs["cspReportUri"] = undefined /*out*/;
            resourceInputs["dsn"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["projectSlug"] = undefined /*out*/;
            resourceInputs["public"] = undefined /*out*/;
            resourceInputs["rateLimit"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["cspReportUri", "dsn"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["organizationSlug", "projectSlug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ProjectKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ProjectKey resource.
 */
export interface ProjectKeyArgs {
    /**
     * Display name of the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Slug of the organization the project belongs to.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Slug of the project the key belongs to.
     */
    projectSlug: pulumi.Input<string>;
    /**
     * Rate limit of the key. Unset accepts every event.
     */
    rateLimit?: pulumi.Input<inputs.KeyRateLimitArgs | undefined>;
}
