// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A GlitchTip project owned by a team. GlitchTip creates one DSN key with every project; its DSN and CSP report URI are exposed as dsn and cspReportUri, additional keys are ProjectKey resources. The resource ID is <organizationSlug>/<projectSlug>. Changing the team adds the new team and removes the old one in place; changing the organization or the slug replaces the project, which deletes its events. Deleting the resource deletes the project.
 */
export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Security endpoint of the default key for Content-Security-Policy report-uri and Expect-CT reports. Empty when defaultKeyId is empty.
     */
    declare public /*out*/ readonly cspReportUri: pulumi.Output<string>;
    /**
     * ID of the key GlitchTip created with the project. Empty when that key was deleted and another one could not be adopted unambiguously.
     */
    declare public /*out*/ readonly defaultKeyId: pulumi.Output<string>;
    /**
     * Public DSN of the default key. Empty when defaultKeyId is empty.
     */
    declare public /*out*/ readonly dsn: pulumi.Output<string>;
    /**
     * Percentage of events to drop for throttling. Defaults to 0.
     */
    declare public readonly eventThrottleRate: pulumi.Output<number | undefined>;
    /**
     * Display name of the project.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Slug of the organization the project belongs to.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * Platform identifier shown in the UI, e.g. javascript or python. Unset clears it.
     */
    declare public readonly platform: pulumi.Output<string | undefined>;
    /**
     * Numeric ID of the project.
     */
    declare public /*out*/ readonly projectId: pulumi.Output<string>;
    /**
     * Effective URL slug of the project.
     */
    declare public /*out*/ readonly projectSlug: pulumi.Output<string>;
    /**
     * URL slug of the project. Derived from the name by GlitchTip when unset; see projectSlug for the effective value.
     */
    declare public readonly slug: pulumi.Output<string | undefined>;
    /**
     * Slug of the team that owns the project. A refresh reports the first attached team when the declared one was detached.
     */
    declare public readonly teamSlug: pulumi.Output<string>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            if (args?.teamSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'teamSlug'");
            }
            resourceInputs["eventThrottleRate"] = args?.eventThrottleRate;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["platform"] = args?.platform;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["teamSlug"] = args?.teamSlug;
            resourceInputs["cspReportUri"] = undefined /*out*/;
            resourceInputs["defaultKeyId"] = undefined /*out*/;
            resourceInputs["dsn"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["projectSlug"] = undefined /*out*/;
        } else {
            resourceInputs["cspReportUri"] = undefined /*out*/;
            resourceInputs["defaultKeyId"] = undefined /*out*/;
            resourceInputs["dsn"] = undefined /*out*/;
            resourceInputs["eventThrottleRate"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["platform"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["projectSlug"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["teamSlug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["cspReportUri", "dsn"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["organizationSlug", "slug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Percentage of events to drop for throttling. Defaults to 0.
     */
    eventThrottleRate?: pulumi.Input<number | undefined>;
    /**
     * Display name of the project.
     */
    name: pulumi.Input<string>;
    /**
     * Slug of the organization the project belongs to.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Platform identifier shown in the UI, e.g. javascript or python. Unset clears it.
     */
    platform?: pulumi.Input<string | undefined>;
    /**
     * URL slug of the project. Derived from the name by GlitchTip when unset; see projectSlug for the effective value.
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * Slug of the team that owns the project. A refresh reports the first attached team when the declared one was detached.
     */
    teamSlug: pulumi.Input<string>;
}
