// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An alert rule of a GlitchTip project: notify the recipients when quantity events arrive within timespanMinutes, and optionally when an uptime monitor of the project fails. Recipients are replaced as a whole on update; GlitchTip matches them by type and URL. The resource ID is <organizationSlug>/<projectSlug>/<alertId>.
 */
export class ProjectAlert extends pulumi.CustomResource {
    /**
     * Get an existing ProjectAlert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ProjectAlert {
        return new ProjectAlert(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:ProjectAlert';

    /**
     * Returns true if the given object is an instance of ProjectAlert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectAlert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectAlert.__pulumiType;
    }

    /**
     * Numeric ID of the alert.
     */
    declare public /*out*/ readonly alertId: pulumi.Output<string>;
    /**
     * Display name of the alert.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * Slug of the organization the project belongs to.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * Slug of the project the alert belongs to.
     */
    declare public readonly projectSlug: pulumi.Output<string>;
    /**
     * Number of events within timespanMinutes that trigger the alert. Defaults to 1.
     */
    declare public readonly quantity: pulumi.Output<number>;
    /**
     * Notification targets. At least one; each type and URL pair once.
     */
    declare public readonly recipients: pulumi.Output<outputs.AlertRecipient[]>;
    /**
     * Window in minutes in which quantity events trigger the alert. Defaults to 1.
     */
    declare public readonly timespanMinutes: pulumi.Output<number>;
    /**
     * Also notify on every failed check of the project's uptime monitors.
     */
    declare public readonly uptime: pulumi.Output<boolean | undefined>;

    /**
     * Create a ProjectAlert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectAlertArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            if (args?.projectSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectSlug'");
            }
            if (args?.recipients === undefined && !opts.urn) {
                throw new Error("Missing required property 'recipients'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["projectSlug"] = args?.projectSlug;
            resourceInputs["quantity"] = (args?.quantity) ?? 1;
            resourceInputs["recipients"] = args?.recipients;
            resourceInputs["timespanMinutes"] = (args?.timespanMinutes) ?? 1;
            resourceInputs["uptime"] = args?.uptime;
            resourceInputs["alertId"] = undefined /*out*/;
        } else {
            resourceInputs["alertId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["projectSlug"] = undefined /*out*/;
            resourceInputs["quantity"] = undefined /*out*/;
            resourceInputs["recipients"] = undefined /*out*/;
            resourceInputs["timespanMinutes"] = undefined /*out*/;
            resourceInputs["uptime"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["organizationSlug", "projectSlug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ProjectAlert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ProjectAlert resource.
 */
export interface ProjectAlertArgs {
    /**
     * Display name of the alert.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Slug of the organization the project belongs to.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Slug of the project the alert belongs to.
     */
    projectSlug: pulumi.Input<string>;
    /**
     * Number of events within timespanMinutes that trigger the alert. Defaults to 1.
     */
    quantity?: pulumi.Input<number | undefined>;
    /**
     * Notification targets. At least one; each type and URL pair once.
     */
    recipients: pulumi.Input<pulumi.Input<inputs.AlertRecipientArgs>[]>;
    /**
     * Window in minutes in which quantity events trigger the alert. Defaults to 1.
     */
    timespanMinutes?: pulumi.Input<number | undefined>;
    /**
     * Also notify on every failed check of the project's uptime monitors.
     */
    uptime?: pulumi.Input<boolean | undefined>;
}
