// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage resources on a GlitchTip instance through its REST API.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'glitchtip';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * API token of a GlitchTip user (Profile > Auth Tokens), or the token issued by a Bootstrap resource. Defaults to the GLITCHTIP_API_TOKEN environment variable. May be omitted for a provider that only creates Bootstrap resources.
     */
    declare public readonly apiToken: pulumi.Output<string>;
    /**
     * Origin of the GlitchTip instance, e.g. https://glitchtip.example.com. Defaults to the GLITCHTIP_BASE_URL environment variable.
     */
    declare public readonly baseUrl: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiToken"] = (args?.apiToken ? pulumi.secret(args.apiToken) : undefined) ?? (utilities.getEnv("GLITCHTIP_API_TOKEN") || "");
            resourceInputs["baseUrl"] = (args?.baseUrl) ?? (utilities.getEnv("GLITCHTIP_BASE_URL") || "");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * API token of a GlitchTip user (Profile > Auth Tokens), or the token issued by a Bootstrap resource. Defaults to the GLITCHTIP_API_TOKEN environment variable. May be omitted for a provider that only creates Bootstrap resources.
     */
    apiToken?: pulumi.Input<string | undefined>;
    /**
     * Origin of the GlitchTip instance, e.g. https://glitchtip.example.com. Defaults to the GLITCHTIP_BASE_URL environment variable.
     */
    baseUrl?: pulumi.Input<string | undefined>;
}
