// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A team of a GlitchTip organization. Teams grant their members access to projects. The resource ID is <organizationSlug>/<slug>; changing either replaces the team, which drops its memberships and project assignments.
 */
export class Team extends pulumi.CustomResource {
    /**
     * Get an existing Team resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Team {
        return new Team(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:Team';

    /**
     * Returns true if the given object is an instance of Team.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Team {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Team.__pulumiType;
    }

    /**
     * Slug of the organization the team belongs to.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * Slug of the team: letters, digits, hyphens and underscores.
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * Numeric ID of the team.
     */
    declare public /*out*/ readonly teamId: pulumi.Output<string>;

    /**
     * Create a Team resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["teamId"] = undefined /*out*/;
        } else {
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["organizationSlug", "slug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Team.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Team resource.
 */
export interface TeamArgs {
    /**
     * Slug of the organization the team belongs to.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Slug of the team: letters, digits, hyphens and underscores.
     */
    slug: pulumi.Input<string>;
}
