// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An uptime monitor of a GlitchTip organization: a periodic HTTP, TCP or certificate check, or a heartbeat endpoint an external job must call. Requires GLITCHTIP_ENABLE_UPTIME on the instance; without it the endpoints answer HTTP 404. Failures notify through project alerts with uptime enabled when projectId is set. The resource ID is <organizationSlug>/<monitorId>. Deleting the resource deletes the monitor with its check history.
 */
export class UptimeMonitor extends pulumi.CustomResource {
    /**
     * Get an existing UptimeMonitor resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): UptimeMonitor {
        return new UptimeMonitor(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'glitchtip:index:UptimeMonitor';

    /**
     * Returns true if the given object is an instance of UptimeMonitor.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UptimeMonitor {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UptimeMonitor.__pulumiType;
    }

    /**
     * Consecutive failed checks before the monitor counts as down and alerts fire, 1 to 100. Defaults to 1.
     */
    declare public readonly confirmationThreshold: pulumi.Output<number>;
    /**
     * Text the response body must contain for GET and POST checks. Empty accepts any body.
     */
    declare public readonly expectedBody: pulumi.Output<string | undefined>;
    /**
     * HTTP status that counts as up. Required for GET and POST; defaults to 200 for them.
     */
    declare public readonly expectedStatus: pulumi.Output<number | undefined>;
    /**
     * URL a Heartbeat monitor expects to be called; empty for other types.
     */
    declare public /*out*/ readonly heartbeatEndpoint: pulumi.Output<string>;
    /**
     * Seconds between checks, 1 to 86400. For Heartbeat monitors the time without a call after which the service counts as down. Defaults to 60.
     */
    declare public readonly intervalSeconds: pulumi.Output<number>;
    /**
     * Numeric ID of the monitor.
     */
    declare public /*out*/ readonly monitorId: pulumi.Output<string>;
    /**
     * Kind of check: Ping, GET, POST, TCP Port, SSL or Heartbeat.
     */
    declare public readonly monitorType: pulumi.Output<enums.MonitorType>;
    /**
     * Display name of the monitor.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Slug of the organization the monitor belongs to.
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * Numeric ID of the project whose alerts report failures, see Project.projectId. Unset leaves the monitor without alerting.
     */
    declare public readonly projectId: pulumi.Output<string | undefined>;
    /**
     * Seconds a check may take, 1 to 60. Unset uses GlitchTip's default of 20.
     */
    declare public readonly timeoutSeconds: pulumi.Output<number | undefined>;
    /**
     * URL to check, or host:port for TCP Port. Not used by Heartbeat monitors. GlitchTip rejects private and internal addresses unless GLITCHTIP_UPTIME_ALLOW_PRIVATE_IPS is on.
     */
    declare public readonly url: pulumi.Output<string | undefined>;

    /**
     * Create a UptimeMonitor resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UptimeMonitorArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.monitorType === undefined && !opts.urn) {
                throw new Error("Missing required property 'monitorType'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            resourceInputs["confirmationThreshold"] = (args?.confirmationThreshold) ?? 1;
            resourceInputs["expectedBody"] = args?.expectedBody;
            resourceInputs["expectedStatus"] = args?.expectedStatus;
            resourceInputs["intervalSeconds"] = (args?.intervalSeconds) ?? 60;
            resourceInputs["monitorType"] = args?.monitorType;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["timeoutSeconds"] = args?.timeoutSeconds;
            resourceInputs["url"] = args?.url;
            resourceInputs["heartbeatEndpoint"] = undefined /*out*/;
            resourceInputs["monitorId"] = undefined /*out*/;
        } else {
            resourceInputs["confirmationThreshold"] = undefined /*out*/;
            resourceInputs["expectedBody"] = undefined /*out*/;
            resourceInputs["expectedStatus"] = undefined /*out*/;
            resourceInputs["heartbeatEndpoint"] = undefined /*out*/;
            resourceInputs["intervalSeconds"] = undefined /*out*/;
            resourceInputs["monitorId"] = undefined /*out*/;
            resourceInputs["monitorType"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organizationSlug"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["timeoutSeconds"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["organizationSlug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(UptimeMonitor.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a UptimeMonitor resource.
 */
export interface UptimeMonitorArgs {
    /**
     * Consecutive failed checks before the monitor counts as down and alerts fire, 1 to 100. Defaults to 1.
     */
    confirmationThreshold?: pulumi.Input<number | undefined>;
    /**
     * Text the response body must contain for GET and POST checks. Empty accepts any body.
     */
    expectedBody?: pulumi.Input<string | undefined>;
    /**
     * HTTP status that counts as up. Required for GET and POST; defaults to 200 for them.
     */
    expectedStatus?: pulumi.Input<number | undefined>;
    /**
     * Seconds between checks, 1 to 86400. For Heartbeat monitors the time without a call after which the service counts as down. Defaults to 60.
     */
    intervalSeconds?: pulumi.Input<number | undefined>;
    /**
     * Kind of check: Ping, GET, POST, TCP Port, SSL or Heartbeat.
     */
    monitorType: pulumi.Input<enums.MonitorType>;
    /**
     * Display name of the monitor.
     */
    name: pulumi.Input<string>;
    /**
     * Slug of the organization the monitor belongs to.
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * Numeric ID of the project whose alerts report failures, see Project.projectId. Unset leaves the monitor without alerting.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Seconds a check may take, 1 to 60. Unset uses GlitchTip's default of 20.
     */
    timeoutSeconds?: pulumi.Input<number | undefined>;
    /**
     * URL to check, or host:port for TCP Port. Not used by Heartbeat monitors. GlitchTip rejects private and internal addresses unless GLITCHTIP_UPTIME_ALLOW_PRIVATE_IPS is on.
     */
    url?: pulumi.Input<string | undefined>;
}
